LazoWeb/Areas/Admin/Controllers/HomeAdminController.cs
using System.Web.Mvc;

namespace LazoWeb.Areas.Admin.Controllers
{
    public class HomeAdminController : BaseController
    {
        // GET: Admin/HomeAdmin
        public ActionResult Index()
        {
            return View();
        }
    }
}

LazoWeb/Areas/Admin/Views/Shared/_LauoutAdmin.cshtml
@using LazoWeb.Models
@{
    ApplicationUser login = (ApplicationUser)Session["login"];
    var admin = Session["admin"];
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="~/Content/img/logo.png" type="image/png" rel="shortcut icon" />
    <title>Admin - @ViewBag.Title</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link href="~/Content/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link href="~/Content/font/css/all.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Content/Admin/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/Admin/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/Content/Admin/dist/css/skins/_all-skins.min.css">
    @*css reponsive table*@
    <link href="~/Content/Admin/dist/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Admin/dist/css/fixedHeader.bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Admin/dist/css/responsive.bootstrap.css" rel="stylesheet" />
    @RenderSection("css",required:false)
    <!-- jQuery 3 -->
    <script src="~/Content/Admin/bower_components/jquery/dist/jquery.min.js"></script>

</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index","HomeAdmin")" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>A</b>LT</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Admin</b></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                @*<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">*@
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    @*<span class="sr-only">Toggle navigation</span>*@
                    <i class="fas fa-align-justify"></i>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="/Content/Admin/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
                                <span class="hidden-xs">
                                    @login.LastName @login.FirstName
                                </span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="/Content/Admin/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                                    <p>
                                        @login.LastName @login.FirstName
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    @if (login.Email != "admin@gmail.com")
                                    {
                                        <div class="pull-left">
                                            <a href="/Manage/ChangePassword" class="btn btn-default btn-flat" id="btn-changePass" data-id="@login.Id">Đổi mật khẩu</a>
                                        </div>
                                        <div class="pull-right">
                                            <a href="@Url.Action("LogOff","Account", new { area = ""})" class="btn btn-default btn-flat">Đăng xuất</a>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="text-center">
                                            <a href="@Url.Action("LogOff","Account", new { area = ""})" class="btn btn-default btn-flat">Đăng xuất</a>
                                        </div>
                                    }
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/Content/Admin/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        @login.LastName @login.FirstName <br />
                        <a href="#"><i class="fa fa-circle text-success"></i> Đang hoạt động</a>
                    </div>
                </div>
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="treeview" id="manage-accounts">
                        <a href="#">
                            <i class="fas fa-tachometer-alt"></i> <span>Quản lý tài khoản</span>
                            <span class="pull-right-container">
                                <i class="fas fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li id="list-accounts"><a href="/Admin/User/GetAllUser"><i class="fas fa-circle-notch"></i> Danh sách tài khoản</a></li>
                        </ul>
                    </li>
                    <li class="treeview" id="manage-customers">
                        <a href="#">
                            <i class="fa fa-table"></i> <span>Quản lý khách hàng</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li id="list-customers"><a href="/Admin/Customers/Index"><i class="fas fa-circle-notch"></i> Danh sách khách hàng</a></li>
                        </ul>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            @RenderBody()
            <!-- /.content -->
        </div>
    </div>
    <!-- ./wrapper -->
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Content/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/Admin/dist/js/adminlte.min.js"></script>
    @*js reponsive table*@
    <script src="~/Scripts/js/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Content/Admin/dist/js/dataTables.fixedHeader.min.js"></script>
    <script src="~/Content/Admin/dist/js/dataTables.responsive.min.js"></script>
    <script src="~/Content/Admin/dist/js/responsive.bootstrap.min.js"></script>
    @*<script src="~/scripts/js/reponsivetable.js"></script>*@
    @*js tooltip*@
    <script src="~/Scripts/js/tooltip.js"></script>
    @RenderSection("script", required: false)
</body>
</html>